"""Initial MAX Lab MVP Platform setup

Revision ID: 018155c10a35
Revises: 
Create Date: 2025-06-25 23:10:31.239226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '018155c10a35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='워크스페이스 이름'),
    sa.Column('slug', sa.String(length=100), nullable=False, comment='URL 친화적 이름'),
    sa.Column('description', sa.Text(), nullable=True, comment='워크스페이스 설명'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성화 상태'),
    sa.Column('settings', sa.JSON(), nullable=True, comment='워크스페이스 설정 JSON'),
    sa.Column('created_by', sa.String(length=255), nullable=False, comment='생성자'),
    sa.Column('updated_by', sa.String(length=255), nullable=True, comment='최종 수정자'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='수정일시'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workspace_active', 'workspaces', ['is_active'], unique=False)
    op.create_index('idx_workspace_created_at', 'workspaces', ['created_at'], unique=False)
    op.create_index('idx_workspace_created_by', 'workspaces', ['created_by'], unique=False)
    op.create_index(op.f('ix_workspaces_id'), 'workspaces', ['id'], unique=False)
    op.create_index(op.f('ix_workspaces_name'), 'workspaces', ['name'], unique=False)
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=True)
    op.create_table('mvp_modules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('module_name', sa.String(length=255), nullable=False, comment='모듈명 (파이썬 모듈명)'),
    sa.Column('display_name', sa.String(length=255), nullable=False, comment='표시명'),
    sa.Column('description', sa.Text(), nullable=True, comment='모듈 설명'),
    sa.Column('version', sa.String(length=50), nullable=True, comment='모듈 버전'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성화 상태'),
    sa.Column('is_installed', sa.Boolean(), nullable=False, comment='설치 상태'),
    sa.Column('config', sa.JSON(), nullable=True, comment='모듈 설정 JSON'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='정렬 순서'),
    sa.Column('icon', sa.String(length=100), nullable=True, comment='아이콘'),
    sa.Column('color', sa.String(length=20), nullable=True, comment='테마 색상'),
    sa.Column('created_by', sa.String(length=255), nullable=False, comment='생성자'),
    sa.Column('updated_by', sa.String(length=255), nullable=True, comment='최종 수정자'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='수정일시'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mvp_module_active', 'mvp_modules', ['is_active'], unique=False)
    op.create_index('idx_mvp_module_installed', 'mvp_modules', ['is_installed'], unique=False)
    op.create_index('idx_mvp_module_name', 'mvp_modules', ['module_name'], unique=False)
    op.create_index('idx_mvp_module_unique', 'mvp_modules', ['workspace_id', 'module_name'], unique=True)
    op.create_index('idx_mvp_module_workspace', 'mvp_modules', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_mvp_modules_id'), 'mvp_modules', ['id'], unique=False)
    op.create_table('workspace_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=False, comment='그룹명'),
    sa.Column('group_display_name', sa.String(length=255), nullable=True, comment='그룹 표시명'),
    sa.Column('permission_level', sa.String(length=50), nullable=False, comment='권한 레벨 (read/write/admin)'),
    sa.Column('created_by', sa.String(length=255), nullable=False, comment='생성자'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='생성일시'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workspace_group_name', 'workspace_groups', ['group_name'], unique=False)
    op.create_index('idx_workspace_group_permission', 'workspace_groups', ['permission_level'], unique=False)
    op.create_index('idx_workspace_group_unique', 'workspace_groups', ['workspace_id', 'group_name'], unique=True)
    op.create_index('idx_workspace_group_workspace', 'workspace_groups', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_workspace_groups_id'), 'workspace_groups', ['id'], unique=False)
    op.create_table('mvp_module_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False, comment='액션 타입 (install/uninstall/activate/deactivate/configure)'),
    sa.Column('message', sa.Text(), nullable=True, comment='로그 메시지'),
    sa.Column('details', sa.JSON(), nullable=True, comment='상세 정보 JSON'),
    sa.Column('created_by', sa.String(length=255), nullable=False, comment='액션 수행자'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='생성일시'),
    sa.ForeignKeyConstraint(['module_id'], ['mvp_modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mvp_module_log_action', 'mvp_module_logs', ['action'], unique=False)
    op.create_index('idx_mvp_module_log_created_at', 'mvp_module_logs', ['created_at'], unique=False)
    op.create_index('idx_mvp_module_log_module', 'mvp_module_logs', ['module_id'], unique=False)
    op.create_index(op.f('ix_mvp_module_logs_id'), 'mvp_module_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mvp_module_logs_id'), table_name='mvp_module_logs')
    op.drop_index('idx_mvp_module_log_module', table_name='mvp_module_logs')
    op.drop_index('idx_mvp_module_log_created_at', table_name='mvp_module_logs')
    op.drop_index('idx_mvp_module_log_action', table_name='mvp_module_logs')
    op.drop_table('mvp_module_logs')
    op.drop_index(op.f('ix_workspace_groups_id'), table_name='workspace_groups')
    op.drop_index('idx_workspace_group_workspace', table_name='workspace_groups')
    op.drop_index('idx_workspace_group_unique', table_name='workspace_groups')
    op.drop_index('idx_workspace_group_permission', table_name='workspace_groups')
    op.drop_index('idx_workspace_group_name', table_name='workspace_groups')
    op.drop_table('workspace_groups')
    op.drop_index(op.f('ix_mvp_modules_id'), table_name='mvp_modules')
    op.drop_index('idx_mvp_module_workspace', table_name='mvp_modules')
    op.drop_index('idx_mvp_module_unique', table_name='mvp_modules')
    op.drop_index('idx_mvp_module_name', table_name='mvp_modules')
    op.drop_index('idx_mvp_module_installed', table_name='mvp_modules')
    op.drop_index('idx_mvp_module_active', table_name='mvp_modules')
    op.drop_table('mvp_modules')
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_name'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_id'), table_name='workspaces')
    op.drop_index('idx_workspace_created_by', table_name='workspaces')
    op.drop_index('idx_workspace_created_at', table_name='workspaces')
    op.drop_index('idx_workspace_active', table_name='workspaces')
    op.drop_table('workspaces')
    # ### end Alembic commands ###